In [11]:
import pandas as pd
import seaborn as sns
import pingouin as pg 
from scipy.stats import chi2_contingency

In [12]:
adults = pd.read_csv('csv_data/adult.csv')

Вопрос:

Связан ли уровень образования (education) с тем, зарабатывает ли человек больше 50K (income)?

In [6]:
adults.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

Так как 2 переменные категориальные, то для проверки статистической значимости используем ХИ квадрат. Проверим сразу на двух библиотеках.

In [11]:
table = pd.crosstab(adults['education'], adults['income'])
table

income        <=50K  >50K
education
10th            871    62
11th           1115    60
12th            400    33
1st-4th         162     6
5th-6th         317    16
7th-8th         606    40
9th             487    27
Assoc-acdm      802   265
Assoc-voc      1021   361
Bachelors      3134  2221
Doctorate       107   306
HS-grad        8826  1675
Masters         764   959
Preschool        51     0
Prof-school     153   423
Some-college   5904  1387

Тест здесь применим, так как обе переменные категориальные. Однако наличие редких категорий может нарушать предпосылки теста (малые ожидаемые частоты), поэтому целесообразно либо объединить категории, либо интерпретировать результаты с осторожностью.

In [10]:
chi2_contingency(table)

Chi2ContingencyResult(statistic=4429.653302288619, pvalue=0.0, dof=15, expected_freq=array([[ 708.3246829 ,  224.6753171 ],
       [ 892.04877   ,  282.95123   ],
       [ 328.72946163,  104.27053837],
       [ 127.54399435,   40.45600565],
       [ 252.81041737,   80.18958263],
       [ 490.43702589,  155.56297411],
       [ 390.22388747,  123.77611253],
       [ 810.05620221,  256.94379779],
       [1049.20119161,  332.79880839],
       [4065.46481988, 1289.53518012],
       [ 313.54565277,   99.45434723],
       [7972.25883726, 2528.74116274],
       [1308.08513252,  414.91486748],
       [  38.71871257,   12.28128743],
       [ 437.29369491,  138.70630509],
       [5535.25751666, 1755.74248334]]))

In [15]:
pg.chi2_independence(adults, x = 'education', y = 'income')

/opt/conda/lib/python3.9/site-packages/pingouin/contingency.py:150: UserWarning: Low count on observed frequencies.
  warnings.warn("Low count on {} frequencies.".format(name))
/opt/conda/lib/python3.9/site-packages/scipy/stats/_stats_py.py:7994: RuntimeWarning: divide by zero encountered in power
  terms = f_obs * ((f_obs / f_exp)**lambda_ - 1)
/opt/conda/lib/python3.9/site-packages/scipy/stats/_stats_py.py:7994: RuntimeWarning: invalid value encountered in multiply
  terms = f_obs * ((f_obs / f_exp)**lambda_ - 1)
/opt/conda/lib/python3.9/site-packages/scipy/stats/_stats_py.py:7991: RuntimeWarning: divide by zero encountered in divide
  terms = 2.0 * special.xlogy(f_exp, f_exp / f_obs)

(income              <=50K         >50K
 education
 10th           708.324683   224.675317
 11th           892.048770   282.951230
 12th           328.729462   104.270538
 1st-4th        127.543994    40.456006
 5th-6th        252.810417    80.189583
 7th-8th        490.437026   155.562974
 9th            390.223887   123.776113
 Assoc-acdm     810.056202   256.943798
 Assoc-voc     1049.201192   332.798808
 Bachelors     4065.464820  1289.535180
 Doctorate      313.545653    99.454347
 HS-grad       7972.258837  2528.741163
 Masters       1308.085133   414.914867
 Preschool       38.718713    12.281287
 Prof-school    437.293695   138.706305
 Some-college  5535.257517  1755.742483,
 income        <=50K  >50K
 education
 10th            871    62
 11th           1115    60
 12th            400    33
 1st-4th         162     6
 5th-6th         317    16
 7th-8th         606    40
 9th             487    27
 Assoc-acdm      802   265
 Assoc-voc      1021   361
 Bachelors      3134  2221
 Doctorate       107   306
 HS-grad        8826  1675
 Masters         764   959
 Preschool        51     0
 Prof-school     153   423
 Some-college   5904  1387,
                  test    lambda         chi2   dof  pval    cramer  power
 0             pearson  1.000000  4429.653302  15.0   0.0  0.368838    1.0
 1        cressie-read  0.666667  4294.554078  15.0   0.0  0.363170    1.0
 2      log-likelihood  0.000000  4224.609208  15.0   0.0  0.360201    1.0
 3       freeman-tukey -0.500000          NaN  15.0   NaN       NaN    NaN
 4  mod-log-likelihood -1.000000          inf  15.0   0.0       inf    NaN
 5              neyman -2.000000          NaN  15.0   NaN       NaN    NaN)

Вывод: Существует статистически значимая связь между образованием и вероятностью получить определенный уровень дохода (pvalue=0.0), умеренная практическая значимость (cramer  = 0.368)